### ISSUE TITLE
Cannot turn on bluetooth in CC

### ISSUE THREAD

**Issue by giang288** [Karimo299/AutoBlue#3]
After the Bluetooth is automatically turned off, it cannot be turned on in Control Center. I need to go to settings page to turn it on.

I disable all other tweaks in iCleaner and the problem still occurs, so I guess its not because of other tweaks.

iPhone X ios 12.1.2 jailbreaked by Unc0ver 3 b46

**Comment by Karimo299** [comment]
Try installing reallcc
