### ISSUE TITLE
autoblue dependency

### ISSUE THREAD

**Issue by abn5x** [Karimo299/AutoBlue#4]
Even though I have Applist installed, it doesn´t want to install becouse it throws an dependency error.

iPad Pro A12X, 12.1.1 Chimera

**Comment by Karimo299** [comment]
Oh right, electra/chimera doesnt accept any caps in the dependence section “appList”. I’ll submit and update when I can, thanks for reporting

**Comment by abn5x** [comment]
okey, thankyou 😊

**Comment by Karimo299** [comment]
Ok, the issue should be fixed on the deb in the packages tab, it also should be up on packix in a bit
